//请求动态数据
export const DYNAMIC_REQUEST_DYNAMIC='DYNAMIC_REQUEST_DYNAMIC';
export const DYNAMIC_REQUEST_DYNAMIC_SUCCESS='DYNAMIC_REQUEST_DYNAMIC_SUCCESS';
export const DYNAMIC_REQUEST_DYNAMIC_FAILURE='DYNAMIC_REQUEST_DYNAMIC_FAILURE';
//改变动态状态
export const DYNAMIC_CHANGE_STATUS = 'DYNAMIC_CHANGE_STATUS';
export const DYNAMIC_CHANGE_STATUS_SUCCESS = 'DYNAMIC_CHANGE_STATUS_SUCCESS';
export const DYNAMIC_CHANGE_STATUS_FAILURE = 'DYNAMIC_CHANGE_STATUS_FAILURE';