export const HEADER_OPTIONS = 'HEADER_OPTIONS';
export const HEADER_BACK_TOP = 'HEADER_BACK_TOP';
export const HEADER_USER_NAME_NULL = 'HEADER_USER_NAME_NULL';
export const HEADER_SEND_USER_NAME = 'HEADER_SEND_USER_NAME';

export const POST_REQUEST_ID = 'POST_REQUEST_ID';
export const POST_REQUEST_ID_SUCCESS = 'POST_REQUEST_ID_SUCCESS';
export const POST_REQUEST_ID_FAILURE = 'POST_REQUEST_ID_FAILURE';

export const POST_PUSH_LIST_ID = 'POST_PUSH_LIST_ID';
