export const HEADER_OPTIONS = 'HEADER_OPTIONS';
export const HEADER_BACK_TOP = 'HEADER_BACK_TOP';
export const HEADER_USER_NAME_NULL = 'HEADER_USER_NAME_NULL';
export const HEADER_SEND_USER_NAME = 'HEADER_SEND_USER_NAME';