export const SEND_POST = 'SEND_POST';
export const SEND_POST_SUCCESS = 'SEND_POST_SUCCESS';
export const SEND_POST_FAILURE = 'SEND_POST_FAILURE';

export const UPDATE_IMG = 'UPDATE_IMG';

export const CHANGE_STATUS = 'CHANGE_STATUS';
