export const POST_INPUT_COMMENT = 'POST_INPUT_COMMENT';
export const POST_INPUT_COMMENT_SUCCESS = 'POST_INPUT_COMMENT_SUCCESS';
export const POST_INPUT_COMMENT_FAILURE = 'POST_INPUT_COMMENT_FAILURE';

export const POST_LIKE_COMMENT = 'POST_LIKE_COMMENT';
export const POST_LIKE_COMMENT_SUCCESS ='POST_LIKE_COMMENT_SUCCESS';
export const POST_LIKE_COMMENT_FAILURE = 'POST_LIKE_COMMENT_FAILURE';

export const POST_COMMENT_REPLY = 'POST_COMMENT_REPLY';
export const POST_COMMENT_REPLY_SUCCESS = 'POST_COMMENT_REPLY_SUCCESS';
export const POST_COMMENT_REPLY_FAILURE = 'POST_COMMENT_REPLY_FAILURE';
