export const HOME_REFRESH = 'HOME_REFRESH';
export const POST_REQUEST_ALL_DATA = 'POST_REQUEST_ALL_DATA';
export const POST_REQUEST_ALL_DATA_SUCCESS = 'POST_REQUEST_ALL_DATA_SUCCESS';
export const POST_REQUEST_ALL_DATA_FAILURE = 'POST_REQUEST_ALL_DATA_FAILURE';

export const POST_COLLECTION = 'POST_COLLECTION';
export const POST_COLLECTION_SUCCESS = 'POST_COLLECTION_SUCCESS';
export const POST_COLLECTION_FAILURE = 'POST_COLLECTION_FAILURE';

export const POST_LIKE = 'POST_LIKE';
export const POST_LIKE_SUCCESS = 'POST_LIKE_SUCCESS';
export const POST_LIKE_FAILURE = 'POST_LIKE_FAILURE';

export const POST_INPUT_COMMENT = 'POST_INPUT_COMMENT';
export const POST_INPUT_COMMENT_SUCCESS = 'POST_INPUT_COMMENT_SUCCESS';
export const POST_INPUT_COMMENT_FAILURE = 'POST_INPUT_COMMENT_FAILURE';

export const POST_LIKE_COMMENT = 'POST_LIKE_COMMENT';
export const POST_LIKE_COMMENT_SUCCESS ='POST_LIKE_COMMENT_SUCCESS';
export const POST_LIKE_COMMENT_FAILURE = 'POST_LIKE_COMMENT_FAILURE';

export const POST_COMMENT_REPLY = 'POST_COMMENT_REPLY';
export const POST_COMMENT_REPLY_SUCCESS = 'POST_COMMENT_REPLY_SUCCESS';
export const POST_COMMENT_REPLY_FAILURE = 'POST_COMMENT_REPLY_FAILURE';
