export const SEARCH_REQUEST_LABEL = 'SEARCH_REQUEST_LABEL';
export const SEARCH_REQUEST_LABEL_SUCCESS = 'SEARCH_REQUEST_LABEL_SUCCESS';
export const SEARCH_REQUEST_LABEL_FAILURE = 'SEARCH_REQUEST_LABEL_FAILURE';

export const SEARCH_REQUEST_TEXT = 'SEARCH_REQUEST_TEXT';
export const SEARCH_REQUEST_TEXT_SUCCESS = 'SEARCH_REQUEST_TEXT_SUCCESS';
export const SEARCH_REQUEST_TEXT_FAILURE = 'SEARCH_REQUEST_TEXT_FAILURE';