export const FOOTER_HOME = 'FOOTER_HOME';
export const FOOTER_SEARCH = 'FOOTER_SEARCH';
export const FOOTER_SEND_POST = 'FOOTER_SEND_POST';
export const FOOTER_DYNAMIC = 'FOOTER_DYNAMIC';
export const FOOTER_ABOUT_ME = 'FOOTER_ABOUT_ME';