export const ABOUTME_CHANGE_FLOATINTERFACE_SHOW = 'ABOUTME_CHANGE_FLOATINTERFACE_SHOW';
export const ABOUTME_CHANGE_FLOATINTERFACE_CLOSE = 'ABOUTME_CHANGE_FLOATINTERFACE_CLOSE';
//
export const LOGIN_GET_REQUEST = 'LOGIN_GET_REQUEST';
export const LOGIN_GET_FAILURE = 'LOGIN_GET_FAILURE';
export const LOGIN_GET_SUCCESS = 'LOGIN_GET_SUCCESS';

