export const ABOUTME_CHANGE_FLOATINTERFACE_SHOW = 'ABOUTME_CHANGE_FLOATINTERFACE_SHOW';
export const ABOUTME_CHANGE_FLOATINTERFACE_CLOSE = 'ABOUTME_CHANGE_FLOATINTERFACE_CLOSE';
//
export const LOGIN_GET_REQUEST = 'LOGIN_GET_REQUEST';
export const LOGIN_GET_FAILURE = 'LOGIN_GET_FAILURE';
export const LOGIN_GET_SUCCESS = 'LOGIN_GET_SUCCESS';

export const CHANGE_USER_INFO = 'CHANGE_USER_INFO';
export const CHANGE_USER_INFO_SUCCESS = 'CHANGE_USER_INFO_SUCCESS';
export const CHANGE_USER_INFO_FAILURE = 'CHANGE_USER_INFO_FAILURE';

//更新用户数据
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_FAILURE = 'UPDATE_USER_INFO_FAILURE';