export const ABOUTME_CHANGE_FLOATINTERFACE_SHOW = 'ABOUTME_CHANGE_FLOATINTERFACE_SHOW';
export const ABOUTME_CHANGE_FLOATINTERFACE_CLOSE = 'ABOUTME_CHANGE_FLOATINTERFACE_CLOSE';
//
export const LOGIN_GET_REQUEST = 'LOGIN_GET_REQUEST';
export const LOGIN_GET_FAILURE = 'LOGIN_GET_FAILURE';
export const LOGIN_GET_SUCCESS = 'LOGIN_GET_SUCCESS';

export const CHANGE_USER_INFO = 'CHANGE_USER_INFO';
export const CHANGE_USER_INFO_SUCCESS = 'CHANGE_USER_INFO_SUCCESS';
export const CHANGE_USER_INFO_FAILURE = 'CHANGE_USER_INFO_FAILURE';

//更新用户数据
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_FAILURE = 'UPDATE_USER_INFO_FAILURE';
//上传头像
export const UPDATE_USER_AVATAR = 'UPDATE_USER_AVATAR';
export const UPDATE_USER_AVATAR_SUCCESS = 'UPDATE_USER_AVATAR_SUCCESS';
export const UPDATE_USER_AVATAR_FAILURE = 'UPDATE_USER_AVATAR_FAILURE';
//保存图片
export const SAVE_IMG = 'SAVE_IMG';
//请求个人所有帖子图片
export const ABOUT_ME_MY_POST = 'ABOUT_ME_MY_POST';
export const ABOUT_ME_MY_POST_SUCCESS = 'ABOUT_ME_MY_POST_SUCCESS';
export const ABOUT_ME_MY_POST_FAILURE = 'ABOUT_ME_MY_POST_FAILURE';
//请求个人收藏帖子图片
export const ABOUT_ME_MY_COLL = 'ABOUT_ME_MY_COLL';
export const ABOUT_ME_MY_COLL_SUCCESS = 'ABOUT_ME_MY_COLL_SUCCESS';
export const ABOUT_ME_MY_COLL_FAILURE = 'ABOUT_ME_MY_COLL_FAILURE';
//请求其他用户信息
export const ABOUT_ME_REQUEST_OTHER_USER_INFO = 'ABOUT_ME_REQUEST_OTHER_USER_INFO';
export const ABOUT_ME_REQUEST_OTHER_USER_INFO_SUCCESS = 'ABOUT_ME_REQUEST_OTHER_USER_INFO_SUCCESS';
export const ABOUT_ME_REQUEST_OTHER_USER_INFO_FAILURE = 'ABOUT_ME_REQUEST_OTHER_USER_INFO_FAILURE';
//关注用户
export const ABOUT_ME_FOLLOW = 'ABOUT_ME_FOLLOW';
export const ABOUT_ME_FOLLOW_SUCCESS = 'ABOUT_ME_FOLLOW_SUCCESS';
export const ABOUT_ME_FOLLOW_FAILURE = 'ABOUT_ME_FOLLOW_FAILURE';
//更改密码
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';
//更改更新状态码
export const CHANGE_UPDATE_STATE = 'CHANGE_UPDATE_STATE';